# Make sure to check the documentation at https://goreleaser.com
project_name: minesweeper
builds:
  - id: minesweeper-cli
    main: ./cmd/minesweeper-cli
    binary: minesweeper-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - id: minesweeper-cli
    image_templates:
      - ghcr.io/bhb603/minesweeper-cli:latest
      - ghcr.io/bhb603/minesweeper-cli:{{ .Tag }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README.md'
